---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env','TYPEORM_MIGRATIONS_DIR') }}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"

  pre_tasks:
    - name: Distribution
      become: false
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      become: false
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      become: false
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: install node modules
      become: true
      shell: |
        apk add --update ansible tar gzip nodejs npm curl
        pip install awscli

  roles:
    - deploy
